/**
 * auxiliares_alpina_map.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Mapa de normalización de nombres de auxiliares ALPINA.
 * Convierte cualquier abreviación o variación que venga del Excel
 * al nombre oficial completo que debe quedar en la base de datos.
 *
 * Uso:
 *   const { normalizarAuxiliar } = require('./auxiliares_alpina_map');
 *   normalizarAuxiliar('JHON GIRALDO')  // → "JHON WILSON GIRALDO CARVAJAL"
 *   normalizarAuxiliar('NO APLICA')     // → "NO APLICA"
 * ─────────────────────────────────────────────────────────────────────────────
 */

const LISTA_OFICIAL_ALPINA = [
    "JHON WILSON GIRALDO CARVAJAL",
    "YHONY ALEXANDER LOPEZ LOPEZ",
    "ROVINSON TORRES RIVERA",
    "JUAN ESTEBAN GALLEGO DIEZ",
    "MILTON GILMER OSORIO CALLE",
    "ARBEY DE JESUS LARGO LARGO",
    "CESAR AUGUSTO CASTILLO LONDOÑO",
    "JUAN JOSE CONTRERAS HERNANDEZ",
    "ANDRES MATEO VILLALBA DIAZ",
    "VICTOR ALFONSO PULGARIN MEJIA",
    "CHRISTIAN DAVID CAICEDO MONTAÑO",
    "JOSE ALEXANDER CONSTAIN PERLAZA",
    "EDWIN MAURICIO GOMEZ GALINDO",
    "ADRIAN FELIPE MARTINEZ ORTEGON",
    "CARLOS ANDRES PINEDA CANO",
    "JUAN ALEJANDRO FRANCO MARIN",
    "LUIS CARLOS CADAVID RESTREPO",
    "BRAHIAN STIVEN VALENCIA IGLESIAS",
    "JOHN EDWAR ZAPATA ACEVEDO",
    "BRANDON STEVEN GIL BAEZ",
    "JUAN MANUEL DELGADO NARVAEZ",
    "YEISON DAVID RENDON SOTO",
    "SEBASTIAN VILLADA VELASQUEZ",
    "CAMILO ANDRES CONTRERAS RIVAS",
    "JUAN DAVID QUINTERO GRAJALES",
    "CRISTIAN FABIAN CAMACHO MARTINEZ",
    "DIORLAN ANTONIO MESA FLOREZ",
    "ANDRES FELIPE RIOS CAICEDO",
    "SANTIAGO HENAO MORALES",
    "CAMILO LEANDRO GUECHE PEÑA",
    "GERMAN GALVEZ CORTES",
    "JHON FREDY MORENO",
    "ELKIN GARCIA OCAMPO",
    "CARLOS ALBERTO JIMENEZ JACOME",
    "MANUEL ALEJANDRO RAMIREZ OVALLE",
    "SAMUEL ANDRES ARIAS ARCILA",
    "VALENTINA GARCIA GOMEZ",
    "DANIELA CASTIBLANCO RAMIREZ",
    "OSCAR MAURICIO RESTREPO MORENO",
    "MICHAEL STEVEN HENAO RODRIGUEZ",
    "JUAN CAMILO COCOMA OROZCO",
    "GERMAN DANIEL PATIÑO VELASQUEZ",
    "JUAN DIEGO FRANCO VERGARA",
];

/**
 * Mapa de alias manuales: variaciones conocidas del Excel → nombre oficial.
 * Agrega aquí cualquier abreviación nueva que aparezca.
 */
const ALIAS_MAP = {
    // JHON WILSON GIRALDO CARVAJAL
    "JHON GIRALDO":             "JHON WILSON GIRALDO CARVAJAL",
    "WILSON GIRALDO":           "JHON WILSON GIRALDO CARVAJAL",

    // YHONY ALEXANDER LOPEZ LOPEZ
    "YHONY LOPEZ":              "YHONY ALEXANDER LOPEZ LOPEZ",
    "YONI LOPEZ":               "YHONY ALEXANDER LOPEZ LOPEZ",

    // ROVINSON TORRES RIVERA
    "ROBINSON TORRES":          "ROVINSON TORRES RIVERA",
    "ROVINSON TORRES":          "ROVINSON TORRES RIVERA",

    // JUAN ESTEBAN GALLEGO DIEZ
    "JUAN GALLEGO":             "JUAN ESTEBAN GALLEGO DIEZ",
    "ESTEBAN GALLEGO":          "JUAN ESTEBAN GALLEGO DIEZ",

    // MILTON GILMER OSORIO CALLE
    "MILTON OSORIO":            "MILTON GILMER OSORIO CALLE",

    // ARBEY DE JESUS LARGO LARGO
    "ARBEY LARGO":              "ARBEY DE JESUS LARGO LARGO",

    // CESAR AUGUSTO CASTILLO LONDOÑO
    "CESAR CASTILLO":           "CESAR AUGUSTO CASTILLO LONDOÑO",

    // JUAN JOSE CONTRERAS HERNANDEZ
    "JUAN CONTRERAS":           "JUAN JOSE CONTRERAS HERNANDEZ",
    "JUAN JOSE CONTRERAS":      "JUAN JOSE CONTRERAS HERNANDEZ",

    // ANDRES MATEO VILLALBA DIAZ
    "MATEO VILLALBA":           "ANDRES MATEO VILLALBA DIAZ",
    "ANDRES VILLALBA":          "ANDRES MATEO VILLALBA DIAZ",

    // VICTOR ALFONSO PULGARIN MEJIA
    "VICTOR PULGARIN":          "VICTOR ALFONSO PULGARIN MEJIA",
    "VICTOR ALFONSO PULGARIN":  "VICTOR ALFONSO PULGARIN MEJIA",

    // CHRISTIAN DAVID CAICEDO MONTAÑO
    "CRISTIAN CAICEDO":         "CHRISTIAN DAVID CAICEDO MONTAÑO",
    "CHRISTIAN CAICEDO":        "CHRISTIAN DAVID CAICEDO MONTAÑO",

    // JOSE ALEXANDER CONSTAIN PERLAZA
    "ALEXANDER COSTAIN":        "JOSE ALEXANDER CONSTAIN PERLAZA",
    "ALEXANDER CONSTAIN":       "JOSE ALEXANDER CONSTAIN PERLAZA",
    "JOSE CONSTAIN":            "JOSE ALEXANDER CONSTAIN PERLAZA",

    // EDWIN MAURICIO GOMEZ GALINDO
    "EDWIN GOMEZ":              "EDWIN MAURICIO GOMEZ GALINDO",

    // ADRIAN FELIPE MARTINEZ ORTEGON
    "ADRIAN MARTINEZ":          "ADRIAN FELIPE MARTINEZ ORTEGON",

    // CARLOS ANDRES PINEDA CANO
    "ANDRES PINEDA":            "CARLOS ANDRES PINEDA CANO",
    "CARLOS PINEDA":            "CARLOS ANDRES PINEDA CANO",

    // JUAN ALEJANDRO FRANCO MARIN
    "JUAN ALEJANDRO":           "JUAN ALEJANDRO FRANCO MARIN",
    "JUAN ALEJANDRO FRANCO":    "JUAN ALEJANDRO FRANCO MARIN",

    // LUIS CARLOS CADAVID RESTREPO
    "LUIS CADAVID":             "LUIS CARLOS CADAVID RESTREPO",

    // BRAHIAN STIVEN VALENCIA IGLESIAS
    "BRAHIAN VALENCIA":         "BRAHIAN STIVEN VALENCIA IGLESIAS",
    "BRAHIAN STIVEN VALENCIA":  "BRAHIAN STIVEN VALENCIA IGLESIAS",

    // JOHN EDWAR ZAPATA ACEVEDO
    "EDWAR ZAPATA":             "JOHN EDWAR ZAPATA ACEVEDO",
    "JOHN ZAPATA":              "JOHN EDWAR ZAPATA ACEVEDO",

    // BRANDON STEVEN GIL BAEZ
    "BRANDON BAEZ":             "BRANDON STEVEN GIL BAEZ",
    "BRANDON GIL":              "BRANDON STEVEN GIL BAEZ",

    // JUAN MANUEL DELGADO NARVAEZ
    "JUAN DELGADO":             "JUAN MANUEL DELGADO NARVAEZ",

    // YEISON DAVID RENDON SOTO
    "YEISON RENDON":            "YEISON DAVID RENDON SOTO",

    // SEBASTIAN VILLADA VELASQUEZ
    "SEBASTIAN VILLADA":        "SEBASTIAN VILLADA VELASQUEZ",

    // CAMILO ANDRES CONTRERAS RIVAS
    "CAMILO CONTRERAS":         "CAMILO ANDRES CONTRERAS RIVAS",

    // JUAN DAVID QUINTERO GRAJALES
    "JUAN QUINTERO":            "JUAN DAVID QUINTERO GRAJALES",
    "JUAN DAVID QUINTERO":      "JUAN DAVID QUINTERO GRAJALES",

    // CRISTIAN FABIAN CAMACHO MARTINEZ
    "CRISTIAN CAMACHO":         "CRISTIAN FABIAN CAMACHO MARTINEZ",

    // DIORLAN ANTONIO MESA FLOREZ
    "DIORLAN":                  "DIORLAN ANTONIO MESA FLOREZ",
    "DIORLAN MESA":             "DIORLAN ANTONIO MESA FLOREZ",

    // ANDRES FELIPE RIOS CAICEDO
    "ANDRES RIOS":              "ANDRES FELIPE RIOS CAICEDO",

    // SANTIAGO HENAO MORALES
    "SANTIAGO HENAO":           "SANTIAGO HENAO MORALES",

    // CAMILO LEANDRO GUECHE PEÑA
    "CAMILO GUECHE":            "CAMILO LEANDRO GUECHE PEÑA",
    "CAMILO LEANDRO":           "CAMILO LEANDRO GUECHE PEÑA",

    // GERMAN GALVEZ CORTES
    "GERMAN GALVEZ":            "GERMAN GALVEZ CORTES",

    // JHON FREDY MORENO
    "JHON MORENO":              "JHON FREDY MORENO",
    "JHON FREDY":               "JHON FREDY MORENO",

    // ELKIN GARCIA OCAMPO
    "ELKIN GARCIA":             "ELKIN GARCIA OCAMPO",

    // CARLOS ALBERTO JIMENEZ JACOME
    "CARLOS JIMENEZ":           "CARLOS ALBERTO JIMENEZ JACOME",

    // MANUEL ALEJANDRO RAMIREZ OVALLE
    "MANUEL RAMIREZ":           "MANUEL ALEJANDRO RAMIREZ OVALLE",
    "MANUEL ALEJANDRO":         "MANUEL ALEJANDRO RAMIREZ OVALLE",

    // SAMUEL ANDRES ARIAS ARCILA
    "SAMUEL ARIAS":             "SAMUEL ANDRES ARIAS ARCILA",

    // VALENTINA GARCIA GOMEZ
    "VALENTINA GARCIA":         "VALENTINA GARCIA GOMEZ",

    // DANIELA CASTIBLANCO RAMIREZ
    "DANIELA CASTIBLANCO":      "DANIELA CASTIBLANCO RAMIREZ",

    // OSCAR MAURICIO RESTREPO MORENO
    "OSCAR RESTREPO":           "OSCAR MAURICIO RESTREPO MORENO",
    "OSCAR MAURICIO RESTREPO":  "OSCAR MAURICIO RESTREPO MORENO",

    // MICHAEL STEVEN HENAO RODRIGUEZ
    "MICHAEL HENAO":            "MICHAEL STEVEN HENAO RODRIGUEZ",
    "STEVEN HENAO":             "MICHAEL STEVEN HENAO RODRIGUEZ",

    // JUAN CAMILO COCOMA OROZCO
    "JUAN COCOMA":              "JUAN CAMILO COCOMA OROZCO",
    "JUAN CAMILO COCOMA":       "JUAN CAMILO COCOMA OROZCO",

    // GERMAN DANIEL PATIÑO VELASQUEZ
    "GERMAN PATIÑO":            "GERMAN DANIEL PATIÑO VELASQUEZ",
    "DANIEL PATIÑO":            "GERMAN DANIEL PATIÑO VELASQUEZ",

    // JUAN DIEGO FRANCO VERGARA
    "JUAN FRANCO":              "JUAN DIEGO FRANCO VERGARA",
    "DIEGO FRANCO":             "JUAN DIEGO FRANCO VERGARA",
};

/**
 * Normaliza un nombre de auxiliar al nombre oficial.
 * 1. Si ya está en la lista oficial → lo devuelve tal cual.
 * 2. Si tiene un alias registrado → lo resuelve.
 * 3. Si no → lo devuelve en mayúsculas con advertencia en consola.
 *
 * @param {string} nombre - Nombre tal como viene del Excel.
 * @returns {string} Nombre oficial normalizado.
 */
function normalizarAuxiliar(nombre) {
    if (!nombre) return '';
    const limpio = nombre.trim().toUpperCase();
    if (!limpio || limpio === 'NO APLICA' || limpio === 'EXTRA' || limpio === 'EXTRA NEGOCIADO') {
        return limpio || 'NO APLICA';
    }

    // 1. Ya está en la lista oficial
    if (LISTA_OFICIAL_ALPINA.includes(limpio)) return limpio;

    // 2. Tiene alias registrado
    if (ALIAS_MAP[limpio]) return ALIAS_MAP[limpio];

    // 3. No se encontró → advertencia para que se agregue el alias
    console.warn(`⚠️  AUXILIAR NO RECONOCIDO: "${limpio}" — agrégalo en ALIAS_MAP en auxiliares_alpina_map.js`);
    return limpio;
}

module.exports = { normalizarAuxiliar, LISTA_OFICIAL_ALPINA, ALIAS_MAP };
